var foodData = [
  {
    "image": "images/Din-Tai-Fung.jpg",
    "name": "Din Tai Fung",
    "location": "Jurong Point Shopping Mall",
    "telNo": "6222 6555",
    "openingHours": "6:00AM - 10:00AM",
    "serviceType": "Dine In",
    "rating": 4.9,
    "priceRange": "~16/pax",
    "diet": "Halal",
    "cuisine": "Fast Food",
    "distance": 400
  },
  {
    "image": "images/subway.png",
    "name": "Subway",
    "location": "Jurong Point",
    "telNo": "1234 5678",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Takeaway, Delivery",
    "rating": 3.3,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Beverages",
    "distance": 790
  },
  {
    "image": "images/astons.jpeg",
    "name": "Astons",
    "location": "JCube",
    "telNo": "1111 1111",
    "openingHours": "11:00AM - 10:00PM",
    "serviceType": "Dine In,Takeaway, Delivery",
    "rating": 4.85,
    "priceRange": "~10/pax",
    "diet": "Normal",
    "cuisine": "Western",
    "distance": 660
  },
  {
    "image": "images/kfc.png",
    "name": "KFC",
    "location": "Westgate",
    "telNo": "6987 5432",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.9,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 809
  },
  {
    "image": "images/sushi express.png",
    "name": "Sushi Express",
    "location": "Jurong Point",
    "telNo": "6123 4567",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.75,
    "priceRange": "~10/pax",
    "diet": "Normal",
    "cuisine": "Japanese",
    "distance": 289
  },
  {
    "image": "images/popeyes.png",
    "name": "Popeyes",
    "location": "Tampines One",
    "telNo": "6543 2198",
    "openingHours": "10:00AM - 9:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.67,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 921
  },
  {
    "image": "images/ajisen.png",
    "name": "Ajisen Ramen",
    "location": "Lot One",
    "telNo": "6689 0982",
    "openingHours": "11:00AM - 9:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.67,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 1902
  },
  {
    "image": "images/pizza hut.png",
    "name": "Pizza Hut",
    "location": "Lot One",
    "telNo": "6147 5386",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.85,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 1723
  },
  {
    "image": "images/4 fingers.png",
    "name": "4 Fingers",
    "location": "JEM",
    "telNo": "6752 9034",
    "openingHours": "10:00AM - 9:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.67,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 218
  },
  {
    "image": "images/llao llao.png",
    "name": "Llao Llao",
    "location": "IMM",
    "telNo": "6136 2468",
    "openingHours": "12:00PM - 8:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.87,
    "priceRange": "~5/pax",
    "diet": "Normal",
    "cuisine": "Dessert",
    "distance": 962
  },
  {
    "image": "images/stuff'd.jpeg",
    "name": "Stuff'd",
    "location": "Lot One",
    "telNo": "6128 9073",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.56,
    "priceRange": "~5/pax",
    "diet": "Normal",
    "cuisine": "Mexican",
    "distance": 1039
  },
  {
    "image": "images/pepper lunch.png",
    "name": "Pepper Lunch",
    "location": "Westgate",
    "telNo": "6128 9073",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.56,
    "priceRange": "~5/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 297
  },
  {
    "image": "images/subway.png",
    "name": "Subway",
    "location": "Westgate",
    "telNo": "6390 9036",
    "openingHours": "9:00AM - 9:00PM",
    "serviceType": "Dine In, Takeaway",
    "rating": 4.84,
    "priceRange": "~7/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 102
  },
  {
    "image": "images/wok hey.jpeg",
    "name": "Wok Hey",
    "location": "Clementi Mall",
    "telNo": "6391 9836",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Takeaway",
    "rating": 4.74,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Chinese",
    "distance": 2189
  },
  {
    "image": "images/srisun.png",
    "name": "Srisun",
    "location": "Yishun Mall",
    "telNo": "6362 9829",
    "openingHours": "11:00AM - 3:00AM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.63,
    "priceRange": "~4/pax",
    "diet": "Normal",
    "cuisine": "Indian",
    "distance": 123
  },
  {
    "image": "images/genki.png",
    "name": "Genki Sushi",
    "location": "Orchard Central",
    "telNo": "6314 0825",
    "openingHours": "10:00AM - 9:00PM",
    "serviceType": "Dine In",
    "rating": 4.95,
    "priceRange": "~20/pax",
    "diet": "Normal",
    "cuisine": "Japanese",
    "distance": 267
  }
];

var foodData1 = [
  {
    "image": "images/playmade.jpeg",
    "name": "Playmade",
    "location": "Jurong Point",
    "telNo": "1234 5678",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Takeaway, Delivery",
    "rating": 4.8,
    "priceRange": "~4/pax",
    "diet": "Normal",
    "cuisine": "Beverages",
    "distance": 790
  },
  {
    "image": "images/macs.jpg",
    "name": "MacDonalds",
    "location": "Chua Chu Kang CC",
    "telNo": "6222 6555",
    "openingHours": "6:00AM - 2:00AM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.9,
    "priceRange": "~6/pax",
    "diet": "Halal",
    "cuisine": "Fast Food",
    "distance": 400
  },
];

var foodData1Sorted = [
  {
  "image": "images/macs.jpg",
  "name": "MacDonalds",
  "location": "Chua Chu Kang CC",
  "telNo": "6222 6555",
  "openingHours": "6:00AM - 2:00AM",
  "serviceType": "Dine In, Takeaway, Delivery",
  "rating": 4.9,
  "priceRange": "~6/pax",
  "diet": "Halal",
  "cuisine": "Fast Food",
  "distance": 400
  },
  {
  "image": "images/playmade.jpeg",
  "name": "Playmade",
  "location": "Jurong Point",
  "telNo": "1234 5678",
  "openingHours": "10:00AM - 10:00PM",
  "serviceType": "Takeaway, Delivery",
  "rating": 4.8,
  "priceRange": "~4/pax",
  "diet": "Normal",
  "cuisine": "Beverages",
  "distance": 790
  },
];

var foodData2 = [
  {
  "image": "images/macs.jpg",
  "name": "MacDonalds",
  "location": "Chua Chu Kang CC",
  "telNo": "6222 6555",
  "openingHours": "6:00AM - 2:00AM",
  "serviceType": "Dine In, Takeaway, Delivery",
  "rating": 4.9,
  "priceRange": "~6/pax",
  "diet": "Halal",
  "cuisine": "Fast Food",
  "distance": 400
  },
  {
  "image": "images/playmade.jpeg",
  "name": "Playmade",
  "location": "Jurong Point",
  "telNo": "1234 5678",
  "openingHours": "10:00AM - 10:00PM",
  "serviceType": "Takeaway, Delivery",
  "rating": 4.8,
  "priceRange": "~4/pax",
  "diet": "Normal",
  "cuisine": "Beverages",
  "distance": 790
  },
  {
  "image": "images/astons.jpeg",
  "name": "Astons",
  "location": "JCube",
  "telNo": "1111 1111",
  "openingHours": "11:00AM - 10:00PM",
  "serviceType": "Dine In,Takeaway, Delivery",
  "rating": 4.85,
  "priceRange": "~10/pax",
  "diet": "Normal",
  "cuisine": "Western",
  "distance": 660
  },
];

var foodData2Sorted = [
  {
    "image": "images/macs.jpg",
    "name": "MacDonalds",
    "location": "Chua Chu Kang CC",
    "telNo": "6222 6555",
    "openingHours": "6:00AM - 2:00AM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.9,
    "priceRange": "~6/pax",
    "diet": "Halal",
    "cuisine": "Fast Food",
    "distance": 400
  },
  {
    "image": "images/astons.jpeg",
    "name": "Astons",
    "location": "JCube",
    "telNo": "1111 1111",
    "openingHours": "11:00AM - 10:00PM",
    "serviceType": "Dine In,Takeaway, Delivery",
    "rating": 4.85,
    "priceRange": "~10/pax",
    "diet": "Normal",
    "cuisine": "Western",
    "distance": 660
  },
  {
    "image": "images/playmade.jpeg",
    "name": "Playmade",
    "location": "Jurong Point",
    "telNo": "1234 5678",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Takeaway, Delivery",
    "rating": 4.8,
    "priceRange": "~4/pax",
    "diet": "Normal",
    "cuisine": "Beverages",
    "distance": 790
  },
];

var foodData3 = [
  {
    "image": "images/macs.jpg",
    "name": "MacDonalds",
    "location": "Chua Chu Kang CC",
    "telNo": "6222 6555",
    "openingHours": "6:00AM - 2:00AM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.9,
    "priceRange": "~6/pax",
    "diet": "Halal",
    "cuisine": "Fast Food",
    "distance": 400
  },
  {
    "image": "images/playmade.jpeg",
    "name": "Playmade",
    "location": "Jurong Point",
    "telNo": "1234 5678",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Takeaway, Delivery",
    "rating": 4.8,
    "priceRange": "~4/pax",
    "diet": "Normal",
    "cuisine": "Beverages",
    "distance": 790
  },
  {
    "image": "images/astons.jpeg",
    "name": "Astons",
    "location": "JCube",
    "telNo": "1111 1111",
    "openingHours": "11:00AM - 10:00PM",
    "serviceType": "Dine In,Takeaway, Delivery",
    "rating": 4.85,
    "priceRange": "~10/pax",
    "diet": "Normal",
    "cuisine": "Western",
    "distance": 660
  },
  {
    "image": "images/4 fingers.png",
    "name": "4 Fingers",
    "location": "JEM",
    "telNo": "6752 9034",
    "openingHours": "10:00AM - 9:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.67,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 218
  },
  {
    "image": "images/llao llao.png",
    "name": "Llao Llao",
    "location": "IMM",
    "telNo": "6136 2468",
    "openingHours": "12:00PM - 8:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.87,
    "priceRange": "~5/pax",
    "diet": "Normal",
    "cuisine": "Dessert",
    "distance": 962
  },
];

var foodData3Sorted = [
  {
    "image": "images/4 fingers.png",
    "name": "4 Fingers",
    "location": "JEM",
    "telNo": "6752 9034",
    "openingHours": "10:00AM - 9:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.67,
    "priceRange": "~6/pax",
    "diet": "Normal",
    "cuisine": "Fast Food",
    "distance": 218
  },
  {
    "image": "images/macs.jpg",
    "name": "MacDonalds",
    "location": "Chua Chu Kang CC",
    "telNo": "6222 6555",
    "openingHours": "6:00AM - 2:00AM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.9,
    "priceRange": "~6/pax",
    "diet": "Halal",
    "cuisine": "Fast Food",
    "distance": 400
  },
  {
    "image": "images/astons.jpeg",
    "name": "Astons",
    "location": "JCube",
    "telNo": "1111 1111",
    "openingHours": "11:00AM - 10:00PM",
    "serviceType": "Dine In,Takeaway, Delivery",
    "rating": 4.85,
    "priceRange": "~10/pax",
    "diet": "Normal",
    "cuisine": "Western",
    "distance": 660
  },
  {
    "image": "images/playmade.jpeg",
    "name": "Playmade",
    "location": "Jurong Point",
    "telNo": "1234 5678",
    "openingHours": "10:00AM - 10:00PM",
    "serviceType": "Takeaway, Delivery",
    "rating": 4.8,
    "priceRange": "~4/pax",
    "diet": "Normal",
    "cuisine": "Beverages",
    "distance": 790
  },
  {
    "image": "images/llao llao.png",
    "name": "Llao Llao",
    "location": "IMM",
    "telNo": "6136 2468",
    "openingHours": "12:00PM - 8:00PM",
    "serviceType": "Dine In, Takeaway, Delivery",
    "rating": 4.87,
    "priceRange": "~5/pax",
    "diet": "Normal",
    "cuisine": "Dessert",
    "distance": 962
  },
];